"""
amc_network_probe.py

Captures all network traffic generated by Playwright loading an AMC showtime
page. Searches every response for seat-data keywords, identifies where
seatingLayout originates, and reports whether any endpoint could realistically
be called directly without a full browser.

No production files are read or modified.

Usage:
    py amc_network_probe.py <AMC_SEAT_URL>

Example:
    py amc_network_probe.py "https://www.amctheatres.com/showtimes/143822631/seats"
"""

import os
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError


# ---------------------------------------------------------------------------
# Keywords to search for in every response body
# ---------------------------------------------------------------------------
SEAT_KEYWORDS = [
    "seatingLayout",
    "LoveSeatLeft",
    "LoveSeatRight",
    "CanReserve",
    "Wheelchair",
    "Companion",
]

# Content-type fragments that are safe to decode as text
TEXT_TYPES = (
    "text/",
    "application/json",
    "application/javascript",
    "application/x-javascript",
    "application/x-www-form-urlencoded",
    "+json",
    "+xml",
    "graphql",
)

# Content-type fragments to skip entirely (binary, no seat data possible)
SKIP_TYPES = (
    "image/",
    "font/",
    "audio/",
    "video/",
    "application/octet-stream",
    "application/wasm",
)

# Snippet window around first keyword hit (chars each side)
SNIPPET_RADIUS = 120


def _is_text(content_type: str) -> bool:
    ct = content_type.lower()
    if any(s in ct for s in SKIP_TYPES):
        return False
    return any(t in ct for t in TEXT_TYPES) or not content_type


def _classify_url(url: str) -> str:
    """Return a short label describing what kind of resource this URL is."""
    parsed = urlparse(url)
    path = parsed.path.lower()

    if path.endswith((".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".ico")):
        return "image"
    if path.endswith((".woff", ".woff2", ".ttf", ".eot")):
        return "font"
    if path.endswith(".css"):
        return "stylesheet"
    if "/_next/static/chunks/" in path or "/_next/static/css/" in path:
        if path.endswith(".js"):
            return "js-bundle"
        return "next-static"
    if "/_next/data/" in path and path.endswith(".json"):
        return "next-data-json"
    if path.endswith(".js") or path.endswith(".mjs"):
        return "javascript"
    if "/graphql" in path or "/api/graphql" in path:
        return "graphql"
    if "/api/" in path:
        return "api-endpoint"
    if "/_next/" in path:
        return "next-internal"
    if path.endswith(("/seats", "/seat")):
        return "main-document"
    if parsed.netloc != urlparse(url).netloc and "amc" not in parsed.netloc:
        return "third-party"
    return "other"


def _classify_by_content_type(content_type: str) -> str:
    ct = content_type.lower()
    if "text/x-component" in ct:
        return "rsc-payload"
    if "text/event-stream" in ct:
        return "sse-stream"
    if "application/json" in ct:
        return "json-api"
    if "graphql" in ct:
        return "graphql"
    if "javascript" in ct:
        return "javascript"
    if "text/html" in ct:
        return "html"
    if "text/plain" in ct:
        return "text"
    return "other"


def _snippet(text: str, keyword: str) -> str:
    idx = text.find(keyword)
    if idx == -1:
        return ""
    start = max(0, idx - SNIPPET_RADIUS)
    end = min(len(text), idx + len(keyword) + SNIPPET_RADIUS)
    raw = text[start:end].replace("\n", " ").replace("\r", "")
    return raw


def _has_auth_indicators(response_entry: dict) -> str:
    """Return a string describing any auth/cookie signals observed."""
    signals = []
    req_headers = response_entry.get("request_headers", {})
    resp_headers = response_entry.get("response_headers", {})
    url = response_entry.get("url", "")

    if req_headers.get("cookie") or req_headers.get("authorization"):
        signals.append("request carried cookies/auth headers")
    if resp_headers.get("set-cookie"):
        signals.append("response sets cookies")
    if "token" in url.lower() or "auth" in url.lower() or "session" in url.lower():
        signals.append("auth-related URL parameter")
    return "; ".join(signals) if signals else "none observed"


# ---------------------------------------------------------------------------
# Main capture function
# ---------------------------------------------------------------------------

def capture_traffic(url: str) -> list[dict]:
    """
    Load url with Playwright, intercept every response, attempt to read its
    body, check for seat keywords. Returns a list of response records.
    """
    records = []

    def on_response(response):
        req = response.request
        content_type = response.headers.get("content-type", "")
        url_str = response.url

        record = {
            "url": url_str,
            "url_classify": _classify_url(url_str),
            "method": req.method,
            "status": response.status,
            "content_type": content_type,
            "content_classify": _classify_by_content_type(content_type),
            "size": 0,
            "keywords_found": [],
            "snippets": {},
            "body_error": None,
            "request_headers": dict(req.headers),
            "response_headers": dict(response.headers),
            "is_text": _is_text(content_type),
        }

        if not _is_text(content_type):
            # Still record it, just skip body read
            records.append(record)
            return

        try:
            body_bytes = response.body()
            record["size"] = len(body_bytes)
            text = body_bytes.decode("utf-8", errors="replace")
        except Exception as exc:
            record["body_error"] = str(exc)
            records.append(record)
            return

        for kw in SEAT_KEYWORDS:
            if kw in text:
                record["keywords_found"].append(kw)
                record["snippets"][kw] = _snippet(text, kw)

        records.append(record)

    print("  Launching headless Chromium...")
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()
        page.on("response", on_response)
        page.goto(url, timeout=120_000)
        try:
            page.wait_for_load_state("networkidle", timeout=15_000)
        except PlaywrightTimeoutError:
            page.wait_for_timeout(12_000)
        browser.close()

    return records


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

W = "=" * 72

def report_all_traffic(records: list[dict]) -> None:
    print(f"\n{W}")
    print("ALL RESPONSES CAPTURED")
    print(W)
    print(f"  {'#':<4} {'Status':<7} {'Size':>9}  {'Type':<20}  URL")
    print(f"  {'-'*4} {'-'*6} {'-'*9}  {'-'*20}  {'-'*50}")

    for i, r in enumerate(records, 1):
        ct_short = r["content_classify"][:20]
        size_str = f"{r['size']:,}" if r["size"] > 0 else ("(skip)" if not r["is_text"] else "(err)")
        kw_flag = "  <-- SEAT DATA" if r["keywords_found"] else ""
        url_display = r["url"]
        if len(url_display) > 90:
            url_display = url_display[:87] + "..."
        print(f"  {i:<4} {r['status']:<7} {size_str:>9}  {ct_short:<20}  {url_display}{kw_flag}")


def report_candidates(records: list[dict], showtime_url: str) -> list[dict]:
    candidates = [r for r in records if r["keywords_found"]]

    print(f"\n{W}")
    print(f"RESPONSES CONTAINING SEAT DATA  ({len(candidates)} found)")
    print(W)

    if not candidates:
        print("  None. seatingLayout keywords not found in any captured response.")
        return candidates

    for i, r in enumerate(candidates, 1):
        print(f"\n  [{i}] {r['url']}")
        print(f"      URL type    : {r['url_classify']}")
        print(f"      Method      : {r['method']}")
        print(f"      Status      : {r['status']}")
        print(f"      Content-Type: {r['content_type']}")
        print(f"      Data type   : {r['content_classify']}")
        print(f"      Size        : {r['size']:,} chars")
        print(f"      Keywords    : {', '.join(r['keywords_found'])}")
        auth = _has_auth_indicators(r)
        print(f"      Auth/cookies: {auth}")

        # Is this the main document?
        if r["url"].rstrip("/") == showtime_url.rstrip("/") or r["url_classify"] == "main-document":
            print("      Source      : MAIN HTML DOCUMENT")
        elif r["content_classify"] == "rsc-payload":
            print("      Source      : RSC STREAMING PAYLOAD (text/x-component)")
        elif r["content_classify"] == "json-api":
            print("      Source      : JSON API ENDPOINT")
        elif r["content_classify"] == "graphql":
            print("      Source      : GRAPHQL ENDPOINT")
        elif r["url_classify"] == "next-data-json":
            print("      Source      : NEXT.JS DATA ENDPOINT (/_next/data/)")
        elif r["url_classify"] in ("js-bundle", "javascript"):
            print("      Source      : JAVASCRIPT BUNDLE (data baked into JS)")
        else:
            print(f"      Source      : {r['content_classify'].upper()} / {r['url_classify'].upper()}")

        # Print a snippet for each keyword
        print("      Snippets:")
        for kw, snippet in r["snippets"].items():
            if snippet:
                display = snippet[:200].replace("\n", " ")
                print(f"        [{kw}] ...{display}...")

    return candidates


def report_analysis(records: list[dict], candidates: list[dict], showtime_url: str) -> None:
    print(f"\n{W}")
    print("STRUCTURAL ANALYSIS")
    print(W)

    total = len(records)
    text_count = sum(1 for r in records if r["is_text"])
    binary_count = total - text_count
    error_count = sum(1 for r in records if r["body_error"])

    print(f"  Total responses captured : {total}")
    print(f"  Text-readable            : {text_count}")
    print(f"  Binary (skipped)         : {binary_count}")
    print(f"  Body read errors         : {error_count}")
    print(f"  Responses with seat data : {len(candidates)}")
    print()

    # Break down all responses by type
    from collections import Counter
    type_counts = Counter(r["content_classify"] for r in records)
    print("  Response type breakdown:")
    for ct, n in type_counts.most_common():
        print(f"    {ct:<25} : {n}")
    print()

    # Classify each candidate
    in_html = any(
        r["content_classify"] == "html" or
        r["url"].rstrip("/") == showtime_url.rstrip("/")
        for r in candidates
    )
    in_rsc = any(r["content_classify"] == "rsc-payload" for r in candidates)
    in_json_api = any(r["content_classify"] == "json-api" for r in candidates)
    in_graphql = any(r["content_classify"] == "graphql" for r in candidates)
    in_next_data = any(r["url_classify"] == "next-data-json" for r in candidates)
    in_js_bundle = any(r["url_classify"] in ("js-bundle", "javascript") for r in candidates)
    in_other = any(
        r["content_classify"] not in ("html", "rsc-payload", "json-api", "graphql")
        and r["url_classify"] not in ("js-bundle", "javascript", "next-data-json")
        for r in candidates
    )

    print("  Where seat data was found:")
    print(f"    Initial HTML document       : {'YES' if in_html else 'no'}")
    print(f"    RSC streaming payload       : {'YES' if in_rsc else 'no'}")
    print(f"    Next.js data endpoint       : {'YES' if in_next_data else 'no'}")
    print(f"    JSON API endpoint           : {'YES' if in_json_api else 'no'}")
    print(f"    GraphQL endpoint            : {'YES' if in_graphql else 'no'}")
    print(f"    JavaScript bundle           : {'YES' if in_js_bundle else 'no'}")
    print(f"    Other                       : {'YES' if in_other else 'no'}")
    print()

    # Directness assessment for each candidate
    print("  Direct-call assessment per candidate:")
    for r in candidates:
        url_display = r["url"]
        if len(url_display) > 60:
            url_display = url_display[:57] + "..."

        ct = r["content_classify"]
        uc = r["url_classify"]
        auth = _has_auth_indicators(r)

        if ct == "html" or r["url"].rstrip("/") == showtime_url.rstrip("/"):
            callability = "NO  -- main document, requires JS to hydrate"
        elif ct == "rsc-payload":
            if auth == "none observed":
                callability = "POSSIBLY -- RSC endpoint, no obvious auth; needs verification"
            else:
                callability = "UNLIKELY -- RSC endpoint requires auth/cookies"
        elif ct in ("json-api", "graphql"):
            if auth == "none observed":
                callability = "LIKELY   -- structured API, no obvious auth observed"
            else:
                callability = "POSSIBLY -- structured API, but auth/cookies observed"
        elif uc == "next-data-json":
            callability = "POSSIBLY -- Next.js data endpoint; URL contains build ID"
        elif uc in ("js-bundle", "javascript"):
            callability = "NO  -- data baked into JS bundle, not an API"
        else:
            callability = "UNKNOWN  -- manual inspection needed"

        print(f"    {url_display}")
        print(f"      -> {callability}")
        print()


def recommend(candidates: list[dict], showtime_url: str) -> None:
    print(f"\n{W}")
    print("VERDICT")
    print(W)

    if not candidates:
        print("  VERDICT: Playwright definitely required")
        print()
        print("  No seat data was found in any captured network response.")
        print("  This is unexpected and warrants further investigation.")
        print("  The data may arrive via a mechanism not captured here")
        print("  (e.g., a Web Worker, a streaming protocol, or late XHR).")
        return

    in_html_only = all(
        r["content_classify"] == "html" or
        r["url"].rstrip("/") == showtime_url.rstrip("/")
        for r in candidates
    )

    in_js_only = all(
        r["url_classify"] in ("js-bundle", "javascript")
        for r in candidates
    )

    has_direct_api = any(
        r["content_classify"] in ("json-api", "graphql")
        for r in candidates
    )

    has_rsc = any(r["content_classify"] == "rsc-payload" for r in candidates)

    has_next_data = any(r["url_classify"] == "next-data-json" for r in candidates)

    has_unauthenticated_api = any(
        r["content_classify"] in ("json-api", "graphql")
        and _has_auth_indicators(r) == "none observed"
        for r in candidates
    )

    rsc_unauthenticated = any(
        r["content_classify"] == "rsc-payload"
        and _has_auth_indicators(r) == "none observed"
        for r in candidates
    )

    if has_unauthenticated_api or has_next_data:
        print("  VERDICT: Direct endpoint may exist")
        print()
        print("  Seat data was found in a structured API or Next.js data endpoint.")
        print("  These endpoints may be directly callable without a full browser.")
        print("  Verification steps:")
        print("    1. Try requests.get() against the exact endpoint URL identified above.")
        print("    2. Pass the same cookies that Playwright sent (check 'Auth/cookies' above).")
        print("    3. If successful, check whether the URL is stable across sessions")
        print("       (i.e., does not embed a short-lived build ID or session token).")

    elif has_rsc and rsc_unauthenticated:
        print("  VERDICT: Direct endpoint may exist")
        print()
        print("  Seat data was found in an RSC payload (text/x-component) with no")
        print("  obvious authentication requirement observed on that specific response.")
        print("  RSC payloads are delivered to the browser as a streaming HTTP response")
        print("  and may be directly fetchable, but they require:")
        print("    - The correct RSC request headers (Next.js checks these)")
        print("    - Potentially the same cookies the browser accumulates during page load")
        print("  Verification steps:")
        print("    1. Identify the exact RSC endpoint URL from the candidate list above.")
        print("    2. Try requests.get() with headers: {'RSC': '1', 'Next-Router-State-Tree': '...'}")
        print("    3. Check whether the response is parseable without the full browser context.")

    elif has_rsc and not rsc_unauthenticated:
        print("  VERDICT: Playwright probably required")
        print()
        print("  Seat data was found in an RSC payload, but the response appears to")
        print("  require auth headers or cookies accumulated during normal page load.")
        print("  Direct fetch of the RSC endpoint without browser session state is")
        print("  unlikely to work without reverse-engineering the session bootstrap.")

    elif in_html_only:
        print("  VERDICT: Playwright definitely required")
        print()
        print("  Seat data was found only in the main HTML document (text/html).")
        print("  This means the seatingLayout JSON is baked into the server-rendered")
        print("  HTML, but only after Next.js RSC streaming completes in the browser.")
        print("  The plain HTTP response (without JS execution) does not contain it,")
        print("  as confirmed by the requests.get() probe. Playwright cannot be removed.")

    elif in_js_only:
        print("  VERDICT: Playwright definitely required")
        print()
        print("  Seat data was found only inside JavaScript bundles.")
        print("  This means availability data is compiled into the JS at build time,")
        print("  which is unlikely for live seat maps. More likely, the keyword match")
        print("  is a type definition or schema rather than live data. Verify manually.")

    else:
        print("  VERDICT: More investigation required")
        print()
        print("  Seat data was found in responses that don't cleanly map to a single")
        print("  directly-callable endpoint. Review the candidate list above.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: py amc_network_probe.py <AMC_SEAT_URL>")
        print()
        print("Example:")
        print('  py amc_network_probe.py "https://www.amctheatres.com/showtimes/143822631/seats"')
        sys.exit(1)

    url = sys.argv[1].strip()
    print("AMC Network Probe")
    print(f"URL: {url}")
    print()
    print("Capturing all network traffic (this takes ~30s)...")

    records = capture_traffic(url)

    if not records:
        print("ERROR: No responses were captured. Check that Playwright is installed.")
        sys.exit(1)

    candidates = []
    report_all_traffic(records)
    candidates = report_candidates(records, url)
    report_analysis(records, candidates, url)
    recommend(candidates, url)
    print()


if __name__ == "__main__":
    main()
